name: Bug report
description: Report a problem so it can be fixed
labels:
  - needs_triage

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a bug in Ansible Builder.**

        If this is a question about using `ansible-builder`, please do not use a new issue for your question.
        New issues should be used only for submitting a new bug report. Please consult the [Community guide](https://docs.ansible.com/projects/builder/en/latest/community/)
        for information on how to submit your question to the [Ansible Forum](https://forum.ansible.com/).

  - type: input
    attributes:
      label: Ansible Builder version
      description: Output from `ansible-builder --version`
    validations:
      required: true

  - type: input
    attributes:
      label: Python version
      description: Output from `python -VV`
    validations:
      required: true

  - type: textarea
    attributes:
      label: Operating System and Environment
      description: Provide relevant information about the operating system and environment
      render: console
      placeholder: RHEL 8, Debian 10, output from `/etc/os-release`, any other relevant information
    validations:
      required: true

  - type: input
    attributes:
      label: Container Runtime
      description: Output from `podman|docker --version`
      placeholder: podman --version
    validations:
      required: true

  - type: textarea
    attributes:
      label: Summary
      description: Briefly explain the problem
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Describe in detail how to reproduce the problem
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Results
      description: What was expected to happen when running the steps above
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Results
      description: What actually happened when running the steps above
    validations:
      required: true
