name: Feature Request
description: Suggest a new feature
labels:
  - needs_triage
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a new feature for Ansible Builder.**

        If you are looking for community support, please visit the [Community guide](https://ansible.readthedocs.io/projects/builder/en/latest/community/)
        for information on how to get in touch.

  - type: textarea
    attributes:
      label: Summary
      description: Describe the new feature and how it would be used.
    validations:
      required: true
